### PR TITLE
EnqueueWriteBuffer added

### PR DESCRIPTION
**Pull request by PassKeyRa**
Hello! I added the EnqueueWriteBuffer, so now it is possible to write buffers that are passed to the kernel

### CODE REVIEW

**Comment by PassKeyRa** [comment]
Any updates? I checked it, it works :)

**Comment by MatejMagat305** [comment]
> Any updates? I checked it, it works :)

I plan fork and convert to purego version, can I use your?

**Comment by johnmichaelboat** [comment]
Hi MatejMagat305,
Sure you can either fork or do a merge-request or we can work together.
Purego is a good idea.
Best

Le ven. 8 mars 2024 à 19:55, MatejMagat305 ***@***.***> a
écrit :

**Comment by MatejMagat305** [comment]
> Hi MatejMagat305, Sure you can either fork or do a merge-request or we can work together. Purego is a good idea. Best Le ven. 8 mars 2024 à 19:55, MatejMagat305

ehm, I invite you to https://github.com/opencl-pure/triple-opencl, but it is still in progress, it is 2.5 fork together (therefore is not clasical fork of ...), but I have no problem after finish merge to more famious project ...

**Comment by johnmichaelboat** [comment]
Thank you, invitation accepted !

Le sam. 9 mars 2024 à 16:10, MatejMagat305 ***@***.***> a
écrit :

**Comment by MasterOfBinary** [comment]
Sorry folks, I don't have time to maintain this repo anymore. Let me know if you want to be added as a collaborator!

This PR looks good though, I'll merge it (i haven't tested it personally).

**Pull request merged**
